"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from dotenv import load_dotenv
load_dotenv()  # Load .env file
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s9p71vstkw&4dc5s)um2fyc5mm*45v_xpv9#a2bz_r@k5409rs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken',
    'djoser',
    'authapp',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOWED_ORIGINS = [
    "https://h2stechsolutions.netlify.app",
    "https://h2s-backend-urrt.onrender.com",
]
CORS_ALLOW_HEADERS = [
    'authorization',
    'content-type',
]

SESSION_COOKIE_AGE = 60 * 60 * 24 * 365  # 1 saal ka session (seconds mein)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Jab browser band ho to session expire na ho
# settings.py mein
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = None  # Indefinite duration
SESSION_COOKIE_AGE = 60 * 60 * 24 * 365 * 10  # 10 saal ke liye set kar sakte hain
# settings.py mein
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Jab browser band ho to session expire ho

CORS_ALLOW_CREDENTIALS = True


  # For development only
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# settings.py

CSRF_TRUSTED_ORIGINS = [
    'https://h2stechsolutions.netlify.app',
    'https://h2stechsolutions.netlify.app/',
    'https://h2s-backend-urrt.onrender.com',
    'https://h2s-backend-urrt.onrender.com/',
    'https://*.cashfree.com',
]
ALLOWED_HOSTS = [
    'h2stechsolutions.netlify.app',
    'h2s-backend-urrt.onrender.com',
    'localhost',
    '127.0.0.1',
]
AUTH_USER_MODEL = 'authapp.CustomUser'
from dotenv import load_dotenv
import os

load_dotenv()  # Load .env
RAZORPAY_KEY_ID = 'rzp_live_Hs9twWPT8yzKjH'  # your live key
RAZORPAY_KEY_SECRET = 'HyXGUjvM94AR8uleEO26atwt'  # never commit this to git!
RAZORPAY_WEBHOOK_SECRET = 'https://h2s-backend-urrt.onrender.com/api/razorpay/webhook/'


# settings.py
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'h2stechsolutions@gmail.com'  # Your official email
EMAIL_HOST_PASSWORD = 'Mp09bc1724_@'  # Use App Password if 2FA enabled
DEFAULT_FROM_EMAIL = 'h2stechsolutions@gmail.com'

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://h2s_db_user:sYF9RaEwgzQvgn5dp9L4GFDKExs3WfIy@dpg-d0fgiva4d50c73esa8r0-a.oregon-postgres.render.com/h2s_db',
        conn_max_age=600,
        ssl_require=True  # Required for Render PostgreSQL
    )
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR / 'static']  # This is for development (optional)

STATIC_ROOT = BASE_DIR / 'staticfiles'  # REQUIRED for production & collectstatic

# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
