# Generated by Django 5.1.7 on 2025-05-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
