# Generated by Django 5.1.7 on 2025-05-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_usercourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCourse',
        ),
    ]
