# Generated by Django 5.1.7 on 2025-05-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_certificaterequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificaterequest',
            old_name='submitted_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='course',
            field=models.CharField(choices=[('htmlcss', 'HTML + CSS'), ('htmlcssjs', 'HTML + CSS + JS'), ('python', 'Python'), ('pythondjango', 'Python + Django'), ('react', 'React'), ('reactjs', 'React + JavaScript')], max_length=20),
        ),
    ]
