# Generated by Django 5.1.7 on 2025-05-13 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_delete_usercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_url', models.CharField(choices=[('/htmlcss89', 'HTML + CSS'), ('/htmlcssjs62', 'HTML + CSS + JS'), ('/python24', 'Python'), ('/pythondjango90', 'Python + Django'), ('/react79', 'React'), ('/reactandjs43', 'React + JavaScript')], max_length=50)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
