# Generated by Django 5.1.7 on 2025-05-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_paymentrecord_usercourseaccess'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercourseaccess',
            unique_together=set(),
        ),
    ]
