# Generated by Django 5.1.7 on 2025-05-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_usercourseaccess_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourseaccess',
            name='course_path',
            field=models.CharField(max_length=100),
        ),
    ]
