# Generated by Django 5.1.7 on 2025-05-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_usercourseaccess_course_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsubmission',
            old_name='submitted_at',
            new_name='created_at',
        ),
    ]
