# Generated by Django 5.1.7 on 2025-05-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_order_updated_at_alter_order_cashfree_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('user', 'course_url')},
        ),
    ]
