# Generated by Django 5.1.7 on 2025-05-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_course_order_id_course_payment_id_course_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
    ]
