# Generated by Django 5.1.7 on 2025-05-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_alter_course_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('user', 'course_url')},
        ),
    ]
