# Generated by Django 5.1.7 on 2025-05-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_course_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
    ]
