# Generated by Django 5.1.7 on 2025-05-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_remove_course_order_id_remove_course_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
    ]
